version: "3.9"
services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    command: jupyter-lab --notebook-dir=/ibm-data-science --no-browser --allow-root --ip=0.0.0.0
    volumes:
      - type: bind
        source: ./
        target: /ibm-data-science
    ports:
      - "8888:8888"
      